

defaults:
    - _self_
    - dataset: null
    - model: null

seed: 0
num_epochs: 50
batch_size: 256
hidden_size: 128
lr: 0.001
use_lr_scheduler: False
use_model_compile: True
wandb:
    use_wandb: False
    entity: "CIDA"
    group_name: "Test"
